services:
  postgre:
    image: postgres:latest
    container_name: dev-logistics-pg
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - pgdata_dev:/var/lib/postgresql

volumes:
  pgdata_dev:
